version: '3.8'

services:
  client:
    build:
      context: ./Client/chat-interface/public
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Client/chat-interface:/Client/chat-interface
      - /Client/chat-interface/node_modules
    depends_on:
      - api

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./API:/API
    command: python3 servico1.py