version: '3.8'




services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web_dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # React/Next.js default port
      - "5000:5000"  # Optional API port
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For hot reloading
    command: npm run dev

  api_service:
    build:
      context: .
      dockerfile: API\Dockerfile_api
    networks:
      - my_network
    ports:
      - "5000:5000"

  client_service:
    build:
      context: .
      dockerfile: Client\Dockerfile_client
    networks:
      - my_network
    depends_on:
      - api_service
      
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:


networks:
  my_network:
